import { User, Certificate } from '../types';
import { supabase } from '../lib/supabase';

// --- Helpers ---

// Map Supabase Auth User to our App's User type
const mapSupabaseUser = (u: any): User => ({
  id: u.id,
  email: u.email || '',
  username: u.user_metadata?.username || u.email?.split('@')[0] || 'User',
  createdAt: u.created_at
});

// Map Database Certificate Row to App Certificate
const mapCertificate = (row: any): Certificate => ({
  id: row.id,
  userId: row.user_id,
  userName: row.user_name,
  videoUrl: row.video_url,
  topic: row.topic,
  score: row.score,
  issuedAt: row.issued_at
});

// --- Auth Services ---

export const registerUser = async (username: string, email: string, password: string): Promise<{ user: User, session: any }> => {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: { username },
      // Redirect back to your app after clicking email link
      emailRedirectTo: window.location.origin 
    }
  });

  if (error) throw new Error(error.message);
  if (!data.user) throw new Error("Registration failed");
  
  return { 
    user: mapSupabaseUser(data.user),
    session: data.session 
  };
};

export const loginUser = async (email: string, password: string): Promise<User> => {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password
  });

  if (error) throw new Error(error.message);
  if (!data.user) throw new Error("Login failed");

  return mapSupabaseUser(data.user);
};

export const logoutUser = async () => {
  await supabase.auth.signOut();
};

export const getCurrentSession = async (): Promise<User | null> => {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session?.user) return null;
  return mapSupabaseUser(session.user);
};

// --- Certificate Services ---

export const saveCertificate = async (cert: Omit<Certificate, 'id' | 'issuedAt'>): Promise<Certificate> => {
  // We insert into Supabase. ID and issued_at are generated by DB/default if not provided.
  
  const dbPayload = {
    user_id: cert.userId,
    user_name: cert.userName,
    video_url: cert.videoUrl,
    topic: cert.topic,
    score: cert.score
  };

  const { data, error } = await supabase
    .from('certificates')
    .insert([dbPayload])
    .select()
    .single();

  if (error) {
    console.error("Save Cert Error", error);
    throw new Error("Failed to save certificate");
  }
  
  return mapCertificate(data);
};

export const getUserCertificates = async (userId: string): Promise<Certificate[]> => {
  const { data, error } = await supabase
    .from('certificates')
    .select('*')
    .eq('user_id', userId)
    .order('issued_at', { ascending: false });

  if (error) throw new Error(error.message);
  return (data || []).map(mapCertificate);
};

export const getCertificateById = async (id: string): Promise<Certificate | null> => {
  const { data, error } = await supabase
    .from('certificates')
    .select('*')
    .eq('id', id)
    .single();

  if (error) return null;
  return mapCertificate(data);
};